### PR TITLE
Remove old lua script that migrates old data, which is so long to execute that it crashes on startup

### PR DESCRIPTION
**Pull request by vizath**
```
Unhandled rejection: ReplyError: BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE.
  ├ error: {"command":"EVALSHA","args":["1958dea8254dc373c186e1d90e614f9c81578aad",1,0,"ResourceRelationship"],"code":"BUSY"}
  Apr 2, 22:47:31 UTC (4c60f290-5599-11e9-87dd-df0ef406fb6e)
Unhandled rejection: ReplyError: ERR Error running script (call to f_1958dea8254dc373c186e1d90e614f9c81578aad): @user_script:14: Script killed by user with SCRIPT KILL...
  ├ error: {"command":"EVALSHA","args":["1958dea8254dc373c186e1d90e614f9c81578aad",1,0,"ResourceRelationship"],"code":"ERR"}
  Apr 2, 22:47:31 UTC (4c636390-5599-11e9-87dd-df0ef406fb6e)
```

### CODE REVIEW

**Comment by devon-sofdesk** [comment]
@vizath Did you apply this fix live to prod?

**Review by devon-sofdesk — APPROVED** [review]

**Comment by vizath** [comment]
I hotpatched only one server for now, but as long as we don't merge and update the package dependencies, it is going to be overwritten with each deployment

**Comment by devon-sofdesk** [comment]
So we merge this, then update the coregraf package.json dependency?

**Comment by vizath** [comment]
Yes

**Review by LalyStana — APPROVED** [review]

**Pull request merged**
